version: "3"

services:
  backup:
    image: lscr.io/linuxserver/rsnapshot
    container_name: backup
    restart: unless-stopped

    volumes:
      - ./config:/config:rw
      - ${BACKUP_DIR}:/.snapshots:rw
      - /home/pi:/data:ro
