version: "3"

services:
  rsnapshot:
    image: lscr.io/linuxserver/rsnapshot
    container_name: rsnapshot
    restart: unless-stopped

    volumes:
      - ./config:/config:rw
      - ${BACKUP_DIR}:/.snapshots:rw
      - /home/pi:/data:ro
