version: "3"

services:
  rsnapshot:
    image: lscr.io/linuxserver/rsnapshot
    container_name: rsnapshot
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.25'

    volumes:
      - ./config:/config:rw
      - ${BACKUP_DIR}:/.snapshots:rw
      - /home/pi:/data:ro
